.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH qtsmbstatusd 7 "Aug 29, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qtsmbstatusd \- qtsmbstatus server : GUI (graphical user interface) for smbstatus
.SH SYNOPSIS
.HP 10
\fBqtsmbstatusd\fR [-d] [-m] [-p port]
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B qtsmbstatusd
commands.
.PP
\fBQtSmbstatus\fR is a GUI (graphical user interface) for smbstatus. It is meant to provide the possibility of administering remote machines.

\fBQtSmbstatus\fR was designed as a client/server system secured with SSL. A login and password is required to log on to server (PAM). The server's application ought to be installed with samba-server.
.PP
.SH "OPTIONS"
-d :           Daemonize
.sp
-p <port> :    TCP port - default = 4443
.sp
-v :           Show qtsmbstatusd version
.sp
-m :           Show debug messages
.sp
--help :       help
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH SEE ALSO
.BR qtsmbstatus (7),
.BR samba (1),
.BR smbstatus (1).
.br
.SH AUTHOR
qtsmbstatusd was written by Daniel Rocher <daniel.rocher@adella.org>.
.PP
This manual page was written by Daniel Rocher <daniel.rocher@adella.org>,
for the Debian project (but may be used by others).
